import { Icon1 } from "@/compornents/Icons";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AddingDarkMode</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="text-center">
        <h1 className="w-[70vw] mt-12 mx-auto text-6xl font-extrabold dark:text-light">
          Keep settings after reloading
        </h1>
        <div
          className="flex flex-col items-center justify-center max-w-lg mx-auto gap-5 bg-light py-16 px-16 mt-6
        border-[3px] border-dark rounded-lg dark:bg-dark dark:text-light dark:border-light
        "
        >
          <Icon1 className="w-[300px]" />
          <p>
            切り替えボタンをクリックしてダークモード/ライトモードを切り替えしたあと、リロードをしても設定を保持。
          </p>
        </div>
      </main>
    </>
  );
}
